@startuml ネジ巻きマン3D化計画 
title ネジ巻きマン
left to right direction

/'
    開発環境 : Unity 2021.3.19f1
    プラットフォーム : PC
'/

package Player{
    enum PlayerStatus{

    }
    class PlayerController{

    }
    class PlayerAnimation{

    }
}
PlayerStatus <.. PlayerController : "参照"
PlayerStatus <.. PlayerAnimation : "参照"

package Gimmicks{
    class GimmickBase{
        
    }

    class Elevator{

    }

    class DeathFloor{

    }
}
note bottom of GimmickBase : 全てのギミックの基底クラス 
GimmickBase <|-- Elevator
GimmickBase <|-- DeathFloor

package Managers{
    enum SceneState{
        StartGame
        PlayGame
        EndGame
    }
    class GameManager{

    }
    class UIManager{

    }
    class SoundManager{

    }
    class SceneTransitionManager{

    }    
}
PlayerController --> GameManager
SceneState <.. GameManager
SceneState <.. UIManager
SceneState <.. SceneTransitionManager
